---
- hosts: all
  become: yes
  vars:
    apache_package: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
    apache_service: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
    document_root: "/var/www/html"

  tasks:
    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy index.html
      copy:
        src: /var/www/html/index.html
        dest: "{{ document_root }}/index.html"
        mode: 0644

    - name: Configure Apache
      lineinfile:
        path: "/etc/{{ apache_service }}/sites-available/000-default.conf"
        regexp: '^[ ]*DocumentRoot '
        line: "        DocumentRoot {{ document_root }}"
      notify:
        - restart apache
      when: ansible_distribution == 'Ubuntu'

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

- hosts: ubuntu
  become: yes
  tasks:
    - name: Enable Apache site
      command: a2ensite 000-default.conf
      notify:
        - restart apache

- hosts: centos
  become: yes
  tasks:
    - name: Copy Apache config
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        mode: 0644
      notify:
        - restart apache
